// LSN_RT_
LSN_INST( OPCODE, "OpCode" )
LSN_INST( PC_L, "PC.L" )
LSN_INST( PC_H, "PC.H" )
LSN_INST( OPERAND, "Operand" )
LSN_INST( OPERAND0, "Operand0" )
LSN_INST( OPERAND1, "Operand1" )
LSN_INST( X, "X" )
LSN_INST( Y, "Y" )
LSN_INST( A, "A" )
LSN_INST( SP, "SP" )
LSN_INST( STATUS, "PSW" )
LSN_INST( C_FLAG, "C flag" )
LSN_INST( Z_FLAG, "Z flag" )
LSN_INST( I_FLAG, "I flag" )
LSN_INST( H_FLAG, "H flag" )
LSN_INST( X_FLAG, "X flag" )
LSN_INST( P_FLAG, "P flag" )
LSN_INST( V_FLAG, "V flag" )
LSN_INST( N_FLAG, "N flag" )
LSN_INST( ADDR_L, "Address.L" )
LSN_INST( ADDR_H, "Address.H" )
LSN_INST( PTR_L, "Pointer.L" )
LSN_INST( PTR_H, "Pointer.H" )
LSN_INST( DUMMY, "Discard" )