// LSN_I_
LSN_INST( ADC, "Add Memory to Accumulator with Carry" )
LSN_INST( ADDW, "Add Memory to Word Register (YA)" )
LSN_INST( AND, "\u201CAND\u201D Memory with Accumulator" )
LSN_INST( AND1, "\u201CAND\u201D Memory Bit with Carry" )
LSN_INST( ASL, "Shift One Bit Left, Memory or Accumulator" )
LSN_INST( BBC, "Branch on Bit Clear" )
LSN_INST( BBS, "Branch on Bit Set" )
LSN_INST( BCC, "Branch on Carry Clear (C=0)" )
LSN_INST( BCS, "Branch on Carry Set (C=1)" )
LSN_INST( BEQ, "Branch if Equal (Z=1)" )
LSN_INST( BMI, "Branch if Minus (N=1)" )
LSN_INST( BNE, "Branch if Not Equal (Z=0)" )
LSN_INST( BPL, "Branch if Plus (N=0)" )
LSN_INST( BRA, "Branch Always" )
LSN_INST( BRK, "Software Break" )
LSN_INST( BVC, "Branch on Overflow Clear (V=0)" )
LSN_INST( BVS, "Branch on Overflow Set (V=1)" )
LSN_INST( CALL, "Call Subroutine" )
LSN_INST( CBNE, "Compare and Branch if Not Equal" )
LSN_INST( CLR1, "Clear Memory Bit" )
LSN_INST( CLRC, "Clear Carry Flag (C=0)" )
LSN_INST( CLRP, "Clear Direct Page Flag (P=0)" )
LSN_INST( CLRV, "Clear Overflow and Half-Carry Flags" )
LSN_INST( CMP, "Compare Memory and Accumulator" )
LSN_INST( CMPW, "Compare Memory and Word Register (YA)" )
LSN_INST( DAA, "Decimal Adjust Accumulator for Addition" )
LSN_INST( DAS, "Decimal Adjust Accumulator for Subtraction" )
LSN_INST( DBNZ, "Decrement Memory or Index and Branch if Not Zero" )
LSN_INST( DEC, "Decrement Memory or Accumulator" )
LSN_INST( DECW, "Decrement Direct Page Word" )
LSN_INST( DI, "Disable Interrupts" )
LSN_INST( DIV, "Divide Word Register (YA) by X" )
LSN_INST( EI, "Enable Interrupts" )
LSN_INST( EOR, "\u201CExclusive-OR\u201D Memory with Accumulator" )
LSN_INST( EOR1, "\u201CExclusive-OR\u201D Memory Bit with Carry" )
LSN_INST( INC, "Increment Memory or Accumulator" )
LSN_INST( INCW, "Increment Direct Page Word" )
LSN_INST( JMP, "Jump to New Location" )
LSN_INST( LSR, "Logical Shift One Bit Right" )
LSN_INST( MOV, "Move Data" )
LSN_INST( MOV1, "Move Bit Data" )
LSN_INST( MOVW, "Move Word Data" )
LSN_INST( MUL, "Multiply Accumulator (A) by Index (Y)" )
LSN_INST( NOP, "No Operation" )
LSN_INST( NOT1, "Invert Memory Bit" )
LSN_INST( NOTC, "Invert Carry Flag" )
LSN_INST( OR, "\u201COR\u201D Memory with Accumulator" )
LSN_INST( OR1, "\u201COR\u201D Memory Bit with Carry" )
LSN_INST( PCALL, "Page Call Subroutine" )
LSN_INST( POP, "Pull Data from Stack" )
LSN_INST( PUSH, "Push Data to Stack" )
LSN_INST( RET, "Return from Subroutine" )
LSN_INST( RETI, "Return from Interrupt" )
LSN_INST( ROL, "Rotate One Bit Left" )
LSN_INST( ROR, "Rotate One Bit Right" )
LSN_INST( SBC, "Subtract Memory from Accumulator with Borrow" )
LSN_INST( SET1, "Set Memory Bit" )
LSN_INST( SETC, "Set Carry Flag (C=1)" )
LSN_INST( SETP, "Set Direct Page Flag (P=1)" )
LSN_INST( SLEEP, "Standby Mode (Sleep)" )
LSN_INST( STOP, "Standby Mode (Stop)" )
LSN_INST( SUBW, "Subtract Memory from Word Register (YA)" )
LSN_INST( TCALL, "Table Call Subroutine" )
LSN_INST( TCLR1, "Test and Clear Memory Bits" )
LSN_INST( TSET1, "Test and Set Memory Bits" )
LSN_INST( XCN, "Exchange Nibbles" )
