LSN_INST( ADC, "Add Memory to Accumulator with Carry" )
LSN_INST( AND, "\u201CAND\u201D Memory with Accumulator" )
LSN_INST( ASL, "Shift One Bit Left, Memory or Accumulator" )
LSN_INST( BCC, "Branch on Carry Clear (C=0)" )
LSN_INST( BCS, "Branch on Carry Set (C=1)" )
LSN_INST( BEQ, "Branch if Equal (Z=1)" )
LSN_INST( BIT, "Bit Test" )
LSN_INST( BMI, "Branch if Result Minus (N=1)" )
LSN_INST( BNE, "Branch if Not Equal (Z=0)" )
LSN_INST( BPL, "Branch if Result Plus (N=0)" )
LSN_INST( BRA, "Branch Always" )
LSN_INST( BRK, "Force Break" )
LSN_INST( BRL, "Branch Always Long" )
LSN_INST( BVC, "Branch on Overflow Clear (V=0)" )
LSN_INST( BVS, "Branch on Overflow Set (V=1)" )
LSN_INST( CLC, "Clear Carry Flag" )
LSN_INST( CLD, "Clear Decimal Mode" )
LSN_INST( CLI, "Clear Interrupt Disable Bit" )
LSN_INST( CLV, "Clear Overflow Flag" )
LSN_INST( CMP, "Compare Memory and Accumulator" )
LSN_INST( COP, "Coprocessor" )
LSN_INST( CPX, "Compare Memory and Index X" )
LSN_INST( CPY, "Compare Memory and Index Y" )
LSN_INST( DEC, "Decrement Memory or Accumulator by One" )
LSN_INST( DEX, "Decrement Index X by One" )
LSN_INST( DEY, "Decrement Index Y by One" )
LSN_INST( EOR, "\u201CExclusive OR\u201D Memory with Accumulator" )
LSN_INST( INC, "Increment Memory or Accumulator by One" )
LSN_INST( INX, "Increment Index X by One" )
LSN_INST( INY, "Increment Index Y by One" )
LSN_INST( JML, "Jump Long" )
LSN_INST( JMP, "Jump to New Location" )
LSN_INST( JSL, "Jump Subroutine Long" )
LSN_INST( JSR, "Jump to New Location Saving Return" )
LSN_INST( LDA, "Load Accumulator with Memory" )
LSN_INST( LDX, "Load Index X with Memory" )
LSN_INST( LDY, "Load Index Y with Memory" )
LSN_INST( LSR, "Shift One Bit Right (Memory or Accumulator)" )
LSN_INST( MVN, "Block Move Negative" )
LSN_INST( MVP, "Block Move Positive" )
LSN_INST( NOP, "No Operation" )
LSN_INST( ORA, "\u201COR\u201D Memory with Accumulator" )
LSN_INST( PEA, "Push Absolute Address" )
LSN_INST( PEI, "Push Indirect Address" )
LSN_INST( PER, "Push Program Counter Relative Address" )
LSN_INST( PHA, "Push Accumulator on Stack" )
LSN_INST( PHB, "Push Data Bank Register on Stack" )
LSN_INST( PHD, "Push Direct Register on Stack" )
LSN_INST( PHK, "Push Program Bank Register on Stack" )
LSN_INST( PHP, "Push Processor Status on Stack" )
LSN_INST( PHX, "Push Index X on Stack" )
LSN_INST( PHY, "Push Index Y on Stack" )
LSN_INST( PLA, "Pull Accumulator from Stack" )
LSN_INST( PLB, "Pull Data Bank Register from Stack" )
LSN_INST( PLD, "Pull Direct Register from Stack" )
LSN_INST( PLP, "Pull Processor Status from Stack" )
LSN_INST( PLX, "Pull Index X from Stack" )
LSN_INST( PLY, "Pull Index Y from Stack" )
LSN_INST( REP, "Reset Status Bits" )
LSN_INST( ROL, "Rotate One Bit Left (Memory or Accumulator)" )
LSN_INST( ROR, "Rotate One Bit Right" )
LSN_INST( RTI, "Return from Interrupt" )
LSN_INST( RTL, "Return from Subroutine Long" )
LSN_INST( RTS, "Return from Subroutine" )
LSN_INST( SBC, "Subtract Memory from Accumulator" )
LSN_INST( SEP, "Set Processor Status Bit" )
LSN_INST( SEC, "Set Carry Flag" )
LSN_INST( SED, "Set Decimal Mode" )
LSN_INST( SEI, "Set Interrupt Disable Status" )
LSN_INST( STA, "Store Accumulator in Memory" )
LSN_INST( STP, "Stop the Clock" )
LSN_INST( STX, "Store Index X in Memory" )
LSN_INST( STY, "Store Index Y in Memory" )
LSN_INST( STZ, "Store Zero in Memory" )
LSN_INST( TAX, "Transfer Accumulator in Index X" )
LSN_INST( TAY, "Transfer Accumulator to Index Y" )
LSN_INST( TCD, "Transfer C Accumulator to Direct Register" )
LSN_INST( TCS, "Transfer C Accumulator to Stack Pointer" )
LSN_INST( TDC, "Transfer Direct Register to C Accumulator" )
LSN_INST( TRB, "Test and Reset Bit" )
LSN_INST( TSB, "Test and Set Bit" )
LSN_INST( TSC, "Transfer Stack Pointer to C Accumulator" )
LSN_INST( TSX, "Transfer Stack Pointer Register to Index X" )
LSN_INST( TXA, "Transfer Index X to Accumulator" )
LSN_INST( TXS, "Transfer Index X to Stack Pointer Register" )
LSN_INST( TXY, "Transfer Index X to Index Y" )
LSN_INST( TYA, "Transfer Index Y to Accumulator" )
LSN_INST( TYX, "Transfer Index Y to Index X" )
LSN_INST( WAI, "Wait for Interrupt" )
LSN_INST( WDM, "Reserved for future use" )
LSN_INST( XBA, "Exchange B and A Accumulator" )
LSN_INST( XCE, "Exchange Carry and Emulation Bits" )
